packages:
  - js/*
catalog:
  "@eslint/js": ^9.31.0
  "@types/cross-spawn": ^6.0.6
  "@types/node": ^22.13.14
  "@types/which": ^3.0.4
  "@types/yargs": ^17.0.33
  "@vitest/eslint-plugin": ^1.3.4
  "@vitest/ui": ^3.2.4
  cspell: ^9.2.0
  eslint: ^9.31.0
  eslint-plugin-import: ^2.32.0
  eslint-plugin-unicorn: ^60.0.0
  execa: ^9.6.0
  picocolors: ^1.0.0
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.1.0
  rimraf: ^6.0.1
  source-map-support: ^0.5.21
  tsx: ^4.20.3
  typescript: ^5.8.3
  typescript-eslint: ^8.39.1
  vitest: ^3.2.4
