[package]
name = "livraison"
version = "0.1.0"
edition = "2024"

[lib]
name = "livraison"
path = "src/lib.rs"
doc = true

[[bin]]
name = "livraison"
path = "src/main.rs"
doc = false

[dependencies]
ar = "0.9.0"
indoc = "2.0.6"


