[package]
name = "livraison"
version = "0.1.0"
edition = "2024"

[lib]
name = "livraison"
path = "src/lib.rs"
doc = true

[[bin]]
name = "livraison"
path = "src/main.rs"
doc = false

[dependencies]
ar = "0.9.0"

[dev-dependencies]
assertables = "9.5.1"
indoc = "2.0.6"
pretty_assertions = "1.4.1"


