use msi_installer::tables::{Control, ControlEvent, Dialog, DialogStyle};

pub fn create_fatal_error_dialog() -> Dialog {
    Dialog {
        dialog: "FatalErrorDialog".to_string(),
        h_centering: 50,
        v_centering: 50,
        width: 370,
        height: 270,
        attributes: DialogStyle::Visible | DialogStyle::Modal,
        title: Some("[ProductName] Setup".to_string()),
        control_first: "Finish".to_string(),
        control_default: Some("Finish".to_string()),
        control_cancel: Some("Finish".to_string()),
    }
}

pub fn create_fatal_error_dialog_controls() -> Vec<Control> {
    vec![
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Title".to_string(),
            type_: "Text".to_string(),
            x: 135,
            y: 20,
            width: 220,
            height: 60,
            attributes: 196611,
            property: None,
            text: Some("{\\TitleFont}[ProductName] [Text_agent] ended prematurely".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Cancel".to_string(),
            type_: "PushButton".to_string(),
            x: 304,
            y: 243,
            width: 56,
            height: 17,
            attributes: 1,
            property: None,
            text: Some("Cancel".to_string()),
            control_next: Some("Back".to_string()),
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Back".to_string(),
            type_: "PushButton".to_string(),
            x: 180,
            y: 243,
            width: 56,
            height: 17,
            attributes: 1,
            property: None,
            text: Some("Back".to_string()),
            control_next: Some("Finish".to_string()),
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "BottomLine".to_string(),
            type_: "Line".to_string(),
            x: 0,
            y: 234,
            width: 374,
            height: 0,
            attributes: 1,
            property: None,
            text: None,
            control_next: None,
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Finish".to_string(),
            type_: "PushButton".to_string(),
            x: 236,
            y: 243,
            width: 56,
            height: 17,
            attributes: 3,
            property: None,
            text: Some("Finish".to_string()),
            control_next: Some("Cancel".to_string()),
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Description1".to_string(),
            type_: "Text".to_string(),
            x: 135,
            y: 70,
            width: 220,
            height: 40,
            attributes: 196611,
            property: None,
            text: Some("[ProductName] [Text_action] ended because of an error. The program has not been installed. This installer can be run again at a later time.".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "FatalErrorDialog".to_string(),
            control: "Description2".to_string(),
            type_: "Text".to_string(),
            x: 135,
            y: 115,
            width: 220,
            height: 20,
            attributes: 196611,
            property: None,
            text: Some("Click the Finish button to exit the [Text_agent].".to_string()),
            control_next: None,
            help: None,
        },
    ]
}

pub fn create_fatal_error_dialog_control_events() -> Vec<ControlEvent> {
    vec![ControlEvent {
        dialog: "FatalErrorDialog".to_string(),
        control: "FatalFinish".to_string(),
        event: "EndDialog".to_string(),
        argument: "Exit".to_string(),
        condition: Some("1".to_string()),
        ordering: Some(19),
    }]
}
