use msi_installer::tables::{Control, Dialog};

pub fn create_progress_dialog() -> Dialog {
    Dialog {
        dialog: "ProgressDialog".to_string(),
        h_centering: 50,
        v_centering: 50,
        width: 370,
        height: 270,
        attributes: 1,
        title: Some("[ProductName] Setup".to_string()),
        control_first: "Cancel".to_string(),
        control_default: Some("Cancel".to_string()),
        control_cancel: Some("Cancel".to_string()),
    }
}

pub fn create_progress_dialog_controls() -> Vec<Control> {
    vec![
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "Title".to_string(),
            type_: "Text".to_string(),
            x: 20,
            y: 15,
            width: 200,
            height: 15,
            attributes: 196611,
            property: None,
            text: Some("{\\BoldFont}[Text_Doing] [ProductName]".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "Cancel".to_string(),
            type_: "PushButton".to_string(),
            x: 304,
            y: 243,
            width: 56,
            height: 17,
            attributes: 3,
            property: None,
            text: Some("Cancel".to_string()),
            control_next: Some("Next".to_string()),
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "Text".to_string(),
            type_: "Text".to_string(),
            x: 35,
            y: 65,
            width: 300,
            height: 25,
            attributes: 3,
            property: None,
            text: Some(
                "Please wait while [ProductName] is [Text_done]. This may take several minutes."
                    .to_string(),
            ),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "ActionText".to_string(),
            type_: "Text".to_string(),
            x: 70,
            y: 105,
            width: 265,
            height: 15,
            attributes: 3,
            property: None,
            text: None,
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "BottomLine".to_string(),
            type_: "Line".to_string(),
            x: 0,
            y: 234,
            width: 374,
            height: 0,
            attributes: 1,
            property: None,
            text: None,
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "Next".to_string(),
            type_: "PushButton".to_string(),
            x: 236,
            y: 243,
            width: 56,
            height: 17,
            attributes: 1,
            property: None,
            text: Some("Next".to_string()),
            control_next: Some("Cancel".to_string()),
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "BannerLine".to_string(),
            type_: "Line".to_string(),
            x: 0,
            y: 44,
            width: 374,
            height: 0,
            attributes: 1,
            property: None,
            text: None,
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "ProgressBar".to_string(),
            type_: "ProgressBar".to_string(),
            x: 35,
            y: 125,
            width: 300,
            height: 10,
            attributes: 65537,
            property: None,
            text: Some("Progress done".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "ProgressDialog".to_string(),
            control: "StatusLabel".to_string(),
            type_: "Text".to_string(),
            x: 35,
            y: 105,
            width: 35,
            height: 10,
            attributes: 3,
            property: None,
            text: Some("Status:".to_string()),
            control_next: None,
            help: None,
        },
    ]
}
