use msi_installer::tables::{Control, Dialog};

pub fn create_remove_dialog() -> Dialog {
    Dialog {
        dialog: "RemoveDialog".to_string(),
        h_centering: 50,
        v_centering: 50,
        width: 370,
        height: 270,
        attributes: 3,
        title: Some("[ProductName] Setup".to_string()),
        control_first: "RemoveRemove".to_string(),
        control_default: Some("RemoveRemove".to_string()),
        control_cancel: Some("RemoveRemove".to_string()),
    }
}

pub fn create_remove_dialog_controls() -> Vec<Control> {
    vec![
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveDescription".to_string(),
            type_: "Text".to_string(),
            x: 135,
            y: 70,
            width: 220,
            height: 50,
            attributes: 196611,
            property: None,
            text: Some("This will remove [ProductName] from your computer. Click Remove to continue or Cancel to exit the uninstaller.".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveTitle".to_string(),
            type_: "Text".to_string(),
            x: 135,
            y: 20,
            width: 220,
            height: 60,
            attributes: 196611,
            property: None,
            text: Some("{\\TitleFont}Uninstall [ProductName]".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveCancel".to_string(),
            type_: "PushButton".to_string(),
            x: 304,
            y: 243,
            width: 56,
            height: 17,
            attributes: 3,
            property: None,
            text: Some("Cancel".to_string()),
            control_next: None,
            help: None,
        },
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveBack".to_string(),
            type_: "PushButton".to_string(),
            x: 180,
            y: 243,
            width: 56,
            height: 17,
            attributes: 1,
            property: None,
            text: Some("Back".to_string()),
            control_next: Some("RemoveRemove".to_string()),
            help: None,
        },
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveBottomLine".to_string(),
            type_: "Line".to_string(),
            x: 0,
            y: 234,
            width: 374,
            height: 0,
            attributes: 1,
            property: None,
            text: None,
            control_next: None,
            help: None,
        },
        Control {
            dialog: "RemoveDialog".to_string(),
            control: "RemoveRemove".to_string(),
            type_: "PushButton".to_string(),
            x: 236,
            y: 243,
            width: 56,
            height: 17,
            attributes: 3,
            property: None,
            text: Some("Remove".to_string()),
            control_next: Some("RemoveCancel".to_string()),
            help: None,
        },
    ]
}
