name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm install
        name: Install dependencies

      - run: pnpm check-version-mismatch
        name: Check dependencies are consistent

      - run: pnpm run build
        name: Build

      - run: pnpm run test
        name: Test

      - run: |
          git status --porcelain
          git diff --no-ext-diff --quiet --exit-code
        name: Check not out of date generated files

      - run: node ./packages/chronus/cmd/cli.mjs pack --pack-destination ./artifacts
        name: Pack

      # Have to use npm as pnpm doesn't respect access.
      - run: node ./packages/chronus/cmd/cli.mjs publish "./artifacts/*.tgz" --access public --engine npm --report-summary ./publish-summary.json
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # To pack and publish as one step
      # - run: node ./packages/chronus/cmd/cli.mjs publish --access public
      #   name: Publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: |
          echo "Publish summary:"
          cat ./publish-summary.json
        name: Log publish summary

      - run: node ./packages/github/cmd/cli.mjs create-releases --repo timotheeguerin/chronus --publish-summary ./publish-summary.json
        name: Create github releases
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
