name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - package

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm install
        name: Install dependencies

      - run: pnpm run build
        name: Build

      - run: pnpm run test
        name: Test

      - run: |
          git status --porcelain
          git diff --no-ext-diff --quiet --exit-code
        name: Check not out of date generated files

      - run: pnpm -r publish --access public --no-git-checks
        name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
