name: Test Installers

on:
  push:
    branches:
      - main
    paths:
      - "js/installers/**"
      - ".github/workflows/test-installers.yml"
  pull_request:
    paths:
      - "js/installers/**"
      - ".github/workflows/test-installers.yml"
  workflow_dispatch:

jobs:
  # Test PowerShell installer natively on Windows
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        shell: ["pwsh", "powershell"]
    steps:
      - uses: actions/checkout@v4
      - name: Test PowerShell installer with ${{ matrix.shell }}
        run: ${{ matrix.shell }} ./install-and-verify.ps1
        working-directory: ./js/installers/test

  # Test shell installer natively on Linux
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shell: ["bash", "zsh"]
    steps:
      - uses: actions/checkout@v4
      - name: Test shell installer with ${{ matrix.shell }}
        run: ${{ matrix.shell }} ./install-and-verify.sh
        working-directory: ./js/installers/test

  # Test shell installer natively on macOS
  macOS:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        shell: ["bash", "zsh"]
    steps:
      - uses: actions/checkout@v4
      - name: Test shell installer with ${{ matrix.shell }}
        run: ${{ matrix.shell }} ./install-and-verify.sh
        working-directory: ./js/installers/test
